---
- name: blacklist dvb modules
  become: yes
  copy:
    src: rtlsdr.conf
    dest: /etc/modprobe.d/rtlsdr.conf
    owner: root
    group: root
    mode: 0644

- name: blacklist Airspy modules
  become: yes
  copy:
    src: airspy-blacklist.conf
    dest: /etc/modprobe.d/airspy-blacklist.conf
    owner: root
    group: root
    mode: 0644

- name: blacklist MiriSDR modules
  become: yes
  copy:
    src: blacklist-msi.conf
    dest: /etc/modprobe.d/blacklist-msi.conf

- name: check if RTL-SDR software is installed
  stat:
    path: /usr/bin/rtl_sdr
  register: rtlsdr_bin

- name: git clone RTL-SDR software
  git:
    repo: https://github.com/rtlsdrblog/rtl-sdr-blog.git
    dest: /tmp/rtl-sdr-blog
    update: no
  register: rtlsdr
  when: not rtlsdr_bin.stat.exists

- name: RTL-SDR-BLOG Package Build
  shell: sudo apt install debhelper ; cd /tmp/rtl-sdr-blog ; sudo dpkg-buildpackage -b --no-sign ; cd .. ; sudo dpkg -i librtlsdr0_*.deb ; sudo dpkg -i librtlsdr-dev_*.deb ; sudo dpkg -i rtl-sdr_*.deb ; sudo cp /tmp/rtl-sdr-blog/rtl-sdr.rules /etc/udev/rules.d/rtl-sdr.rules ; sudo rm -rf /tmp/rtl-sdr-blog /tmp/librtlsdr* /tmp/rtl-sdr*
  when: rtlsdr.changed

- name: link RTL-SDR files
  become: yes
  command: ldconfig
  when: rtlsdr.changed

- name: Unload kernel modules (ignore if error, that means the stock driver wasn't present which is good)
  become: yes
  command: modprobe -r msi2500 msi001
  ignore_errors: yes  # Ignore errors if the modules are not loaded

- name: copy Airspy udev rules
  become: yes
  copy:
    src: 52-airspy.rules
    dest: /etc/udev/rules.d/52-airspy.rules
    owner: root
    group: root
    mode: 0644
...
